#!/data/data/com.termux/files/usr/bin/sh
## This file is executed during VNC server
## startup:#!/data/data/com.termux/files/usr/bin/bash
dbus-launch --exit-with-session mate-session &

# Launch terminal emulator Aterm.
# Requires package 'aterm'.
aterm -geometry 80x24+10+10 -ls &

# Launch Tab Window Manager.
# Requires package 'xorg-twm'.
twm &
